backend:
  name: github
  repo: abbassmokashar/website # IMPORTANT: Please verify this is your correct GitHub repository (username/repository_name)
  branch: main # IMPORTANT: Please verify this is your correct branch (e.g., main, master)
  # Optional: You can uncomment and customize commit messages
  # commit_messages:
  #   create: 'Create {{collection}} “{{slug}}”'
  #   update: 'Update {{collection}} “{{slug}}”'
  #   delete: 'Delete {{collection}} “{{slug}}”'
  #   uploadMedia: 'Upload “{{path}}”'
  #   deleteMedia: 'Delete “{{path}}”'

media_folder: "assets/uploads" # Relative to the root of your repository. Stores uploaded images here.
public_folder: "/website/assets/uploads" # The public path for media. If your site is at abbassmokashar.github.io/website/, this should be correct.

collections:
  - name: "portfolio"
    label: "Portfolio"
    folder: "_portfolio" # Markdown files for portfolio items will be stored here.
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "portfolio_item"} # Optional: for Jekyll or other SSGs
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "image", widget: "image", required: false}
      - {label: "Categories/Tags", name: "tags", widget: "string", required: false, hint: "Comma-separated values, e.g., Web Development, Branding"}
      - {label: "Short Description (for listing pages)", name: "description", widget: "text"}
      - {label: "Main Content", name: "body", widget: "markdown"}

  - name: "services"
    label: "Services"
    folder: "_services" # Markdown files for services will be stored here.
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "service_item"} # Optional: for Jekyll or other SSGs
      - {label: "Service Name", name: "title", widget: "string"}
      - {label: "Icon (e.g., class name for an icon font)", name: "icon", widget: "string", required: false}
      - {label: "Short Description", name: "description", widget: "text"}
      - {label: "Detailed Content", name: "body", widget: "markdown"}

# Optional: If your site uses a specific CSS for previews in the editor
# editor:
#   preview_styles: ['/website/path/to/your/main.css']

